Changes as per standard
fortinet-fortisoar/connector-wiz-io pull request #2
Opened 2024-01-04 17:16 UTC by cs-renuka-andhale

#### Descriptions:
Made the changes as per connector standard.

2024-01-05 09:21 UTC, cs-utkarsh-surana requested changes

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/connector.py
> +    Copyright end
Change it to 2024

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/info.json
> +  "publisher": "Julian Petersohn",
Change it to Fortinet

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/info.json
> +  "icon_small_name": "download.png",
Both small and large images are referring to same image

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/info.json
> +        "tooltip": "URL wich is used to retrieve OAuth Token from. The URL can be found at the Service Account page."
Spelling mistakes of 'which' also complete the sentence by specifying the source.

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/info.json
> +          "value": 100,
Description keys are missing in most of the parameter.

2024-01-05 09:21 UTC, cs-utkarsh-surana commented on wiz-io/utils.py
> +import requests
copy right missing

2024-01-05 09:25 UTC, cs-utkarsh-surana requested changes

2024-01-05 09:25 UTC, cs-utkarsh-surana commented on wiz-io/playbooks/Sample - Wiz.io - 1.0.0.json
> +null
Remove this and add the palybooks file

2024-01-05 09:25 UTC, cs-utkarsh-surana commented on wiz-io/operations.py
> +    Copyright (c) 2023 Fortinet Inc
Change the year

2024-01-05 09:25 UTC, cs-utkarsh-surana commented on wiz-io/info.json
> +  "description": "Wiz provides a comprehensive analysis engine that integrates: Cloud Security Posture Management (CSPM) Kubernetes Security Posture Management (KSPM) Cloud Workload Protection (CWPP)
Add standard keys which are missing eg. cs_approved, cs_compatible

2024-01-12 06:08 UTC, cs-prerna-joshi commented on wiz-io/info.json
> +  "category": "Asset Management",
incorrect category

2024-01-12 06:08 UTC, cs-prerna-joshi commented on wiz-io/info.json
> +  "publisher": "Fortinet CSE",
```suggestion
  "publisher": "Fortinet",
```

2024-01-12 06:21 UTC, cs-renuka-andhale commented on wiz-io/info.json
> +  "category": "Asset Management",
Please suggest category ?

2024-01-16 12:11 UTC, merged